### ISSUE TITLE
Approve and Deny Businesses

### ISSUE THREAD

**Issue by joshualipton** [ctc-uci/fph-frontend#45]
## Overview

*"Computer programmers obtain quasi-magical, superhuman coding ability when they have a blood alcohol concentration percentage between 0.129% and 0.138%" - Former CEO of Microsoft*

### Running the program
1. Clone the repo through `git clone`
2. Navigate to the directory of your `fph-frontend` repo using the `cd` command.
3. Run `git checkout dev` and then `git pull`.
4. Create a branch off the `dev` branch in `fph-frontend`. For the name of the branch, use what the title of this issue as. Use `git checkout -b <insert_branch_name>`.
5. Install the necessary dependencies through running `yarn`. Test that your application works by running `yarn format` followed by `yarn dev` 
6. Create your necessary code through creating files within the `component` folder.
7. Run the code with `yarn` (to install), `yarn format` (to format the code), and `yarn start` (to start the program).
8. Access `localhost:3000/`.

### Task
[Toast](https://www.figma.com/file/VkH80LtHkl1Ck76v88fTvk/FPH-Wireframes?type=design&node-id=2171-26655&mode=design&t=mrkiFSqid6eiA4mS-0)
[Modal](https://www.figma.com/file/VkH80LtHkl1Ck76v88fTvk/FPH-Wireframes?type=design&node-id=2171-26939&mode=design&t=mrkiFSqid6eiA4mS-4)

You will be implementing the functionality to approve and deny pending businesses. You can reference this task to find the logic that created the Approve and Deny buttons. They currently have no logic behind them. When the button is clicked, you should bring the user back to the pending applilcation table page and the toast should pop up in the bottom right corner. Show the green toast for an approved business and a yellow one for a denied business. Lastly, when a user clicks on the modal they should be able to undo the action with the modal linked above showing up. If the action is undone, the status of the business should return to pending and they should appear in the pending businesses table again. 

Reference the documentation for [Toast](https://chakra-ui.com/docs/components/toast) and [Modal](https://chakra-ui.com/docs/components/modal)

### Support

Feel free to reach out to Madhu and Josh on Slack/Messenger for assistance.

**Comment by MaanPatel2005** [comment]
Issue was resolved
